// @ts-check
/** A plausible plain-English request for each agent: composer placeholders and the demo's autopilot. */
export const EXAMPLE_TASKS = /** @type {Readonly<Record<string, string>>} */ ({
  powershell: 'Back up my Documents folder to D:\\Backup every night and keep 7 days',
  zsh: 'A script that cleans up node_modules folders older than 30 days',
  bash: 'A script that checks if my websites are up and emails me if not',
  python: 'Rename all photos in a folder by the date they were taken',
  javascript: 'A small web page that converts between time zones',
  typescript: 'A typed client for the GitHub API that lists my repos',
  java: 'A command-line bank account simulator with tests',
  csharp: 'A Windows tray app that reminds me to stretch every hour',
  go: 'A fast tool that finds duplicate files in a folder',
  c: 'A tiny program that counts words in a text file',
  cpp: 'A console snake game',
  rust: 'A CLI that converts CSV files to JSON',
  php: 'A contact form that saves messages to a SQLite database',
  ruby: 'A script that turns my Markdown notes into an HTML site',
  swift: 'A SwiftUI to-do list app',
  kotlin: 'An Android screen that shows the weather for my city',
  frontend: 'A responsive landing page for my portfolio',
  backend: 'A REST API for a recipe app',
  fullstack: 'A habit tracker with a web UI and a database',
  devops: 'A GitHub Actions workflow that runs my tests on every push',
  qa: 'Write tests for the code in my project and report bugs',
  database: 'Design a database schema for a small online store',
  writer: 'Write a clear README for my project',
  security: 'Review my project for security problems and fix the safe ones',
  'tech-lead': 'Review the code in this folder and suggest an architecture',
});
